language: php
php:
  - 7.0
 
script: phpunit -v
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
 
env:
 global:
   - GH_REF: git@github.com:huguifeng/999.git