language: php
php:
  - 5.4
  - 7.0
  - 5.6

# S: Build Lifecycle

script: phpunit -v
before_script:
  - composer install
  - cd tests
before_install:                      
  - composer self-update
install:                             
  - composer install --no-interaction --prefer-source
env:
 global:
   - GH_REF: git@github.com:huguifeng/999.git